-- ============================================================
-- Chef-It: Database Creation Script
-- Creates the chef_it database, the Restaurants table, and
-- populates it with the full merged and deduplicated dataset.
-- ============================================================

CREATE DATABASE IF NOT EXISTS chef_it;
USE chef_it;

DROP TABLE IF EXISTS Restaurants;

CREATE TABLE Restaurants (
    RestaurantName VARCHAR(100),
    AmbienceDescription VARCHAR(50),
    SpecialtyCuisine VARCHAR(50),
    Price VARCHAR(10),
    Delivery VARCHAR(3),
    Location VARCHAR(100),
    Rating DECIMAL(3,1),
    VegOptions VARCHAR(3),
    Reservations VARCHAR(3),
    GlutenFree VARCHAR(3),
    DriveThru VARCHAR(3),
    KidsMenu VARCHAR(3),
    PetFriendly VARCHAR(3),
    ProvidesOffer VARCHAR(3),
    PRIMARY KEY (RestaurantName, Location)
);

START TRANSACTION;

INSERT INTO Restaurants (
    RestaurantName, AmbienceDescription, SpecialtyCuisine, Price, Delivery,
    Location, Rating, VegOptions, Reservations, GlutenFree, DriveThru,
    KidsMenu, PetFriendly, ProvidesOffer
) VALUES
('La Cuenta Restaurant', 'Fancy', 'Spanish Cuisine', '$$$$', 'No', 'Dubai Hills', 4.3, 'Yes', 'Yes', 'No', 'No', 'No', 'No', 'No'),
('Pasta Palace', 'Cozy', 'Italian Cuisine', '$$', 'Yes', 'Downtown', 4.5, 'Yes', 'Yes', 'Yes', 'No', 'Yes', 'No', 'Yes'),
('Sushi World', 'Modern', 'Japanese Cuisine', '$$$', 'Yes', 'Marina Bay', 4.7, 'Yes', 'Yes', 'No', 'No', 'Yes', 'No', 'No'),
('Burger Town', 'Casual', 'American Cuisine', '$', 'Yes', 'City Center', 4, 'No', 'No', 'No', 'Yes', 'Yes', 'No', 'Yes'),
('Curry House', 'Traditional', 'Indian Cuisine', '$$', 'Yes', 'Old Town', 4.6, 'Yes', 'Yes', 'Yes', 'No', 'Yes', 'No', 'Yes'),
('Green Leaf', 'Eco-friendly', 'Vegan Cuisine', '$$', 'Yes', 'Eco Park', 4.8, 'Yes', 'No', 'Yes', 'No', 'Yes', 'Yes', 'No'),
('Pizza Plaza', 'Family-friendly', 'Italian Cuisine', '$$', 'Yes', 'Suburbs', 4.2, 'Yes', 'No', 'Yes', 'No', 'Yes', 'No', 'Yes'),
('Taco Time', 'Vibrant', 'Mexican Cuisine', '$', 'Yes', 'Beachfront', 4.1, 'Yes', 'No', 'No', 'Yes', 'Yes', 'No', 'Yes'),
('Dragon Delight', 'Elegant', 'Chinese Cuisine', '$$$', 'Yes', 'Chinatown', 4.5, 'Yes', 'Yes', 'Yes', 'No', 'Yes', 'No', 'No'),
('The French Bistro', 'Romantic', 'French Cuisine', '$$$$', 'No', 'Historic District', 4.6, 'Yes', 'Yes', 'Yes', 'No', 'No', 'No', 'No'),
('Seafood Shack', 'Casual', 'Seafood', '$$$', 'Yes', 'Waterfront', 4.3, 'No', 'No', 'Yes', 'No', 'Yes', 'No', 'Yes'),
('Kebab Kingdom', 'Traditional', 'Middle Eastern Cuisine', '$$', 'Yes', 'Cultural Quarter', 4.4, 'Yes', 'No', 'Yes', 'No', 'Yes', 'No', 'Yes'),
('Burger Bonanza', 'Casual', 'American Cuisine', '$$', 'Yes', 'City Center', 4.1, 'Yes', 'No', 'No', 'Yes', 'Yes', 'No', 'Yes'),
('Dim Sum Delight', 'Modern', 'Chinese Cuisine', '$$$', 'Yes', 'Chinatown', 4.5, 'Yes', 'Yes', 'Yes', 'No', 'Yes', 'No', 'No'),
('Spice Symphony', 'Vibrant', 'Indian Cuisine', '$$', 'Yes', 'Old Town', 4.6, 'Yes', 'Yes', 'Yes', 'No', 'Yes', 'No', 'Yes'),
('Falafel Factory', 'Eco-friendly', 'Middle Eastern Cuisine', '$$', 'Yes', 'Eco Park', 4.8, 'Yes', 'No', 'Yes', 'No', 'Yes', 'Yes', 'No'),
('Tandoori Treats', 'Traditional', 'Indian Cuisine', '$$', 'Yes', 'Cultural Quarter', 4.6, 'Yes', 'Yes', 'Yes', 'No', 'Yes', 'No', 'Yes'),
('The Noodle House', 'Modern', 'Asian Fusion', '$$', 'Yes', 'Downtown', 4.5, 'Yes', 'No', 'Yes', 'No', 'Yes', 'No', 'Yes'),
('Pho Paradise', 'Casual', 'Vietnamese Cuisine', '$$', 'Yes', 'Market District', 4.6, 'Yes', 'No', 'Yes', 'No', 'Yes', 'No', 'Yes'),
('Bistro Italiano', 'Romantic', 'Italian Cuisine', '$$$', 'No', 'Historic Quarter', 4.7, 'Yes', 'Yes', 'Yes', 'No', 'Yes', 'No', 'No'),
('Greek Taverna', 'Traditional', 'Greek Cuisine', '$$', 'Yes', 'Old Town', 4.5, 'Yes', 'Yes', 'Yes', 'No', 'Yes', 'No', 'Yes'),
('Saffron Lounge', 'Elegant', 'Indian Cuisine', '$$$$', 'No', 'Financial District', 4.8, 'Yes', 'Yes', 'Yes', 'No', 'No', 'No', 'No'),
('Burger Bistro', 'Casual', 'American Cuisine', '$$', 'Yes', 'City Center', 4.2, 'Yes', 'No', 'No', 'Yes', 'Yes', 'No', 'Yes'),
('Fish & Chips Corner', 'Casual', 'British Cuisine', '$', 'Yes', 'Seaside', 4.1, 'No', 'No', 'No', 'Yes', 'Yes', 'No', 'Yes'),
('Korean BBQ', 'Vibrant', 'Korean Cuisine', '$$$', 'Yes', 'Asian District', 4.6, 'Yes', 'Yes', 'Yes', 'No', 'Yes', 'No', 'No'),
('Taco Fiesta', 'Lively', 'Mexican Cuisine', '$$', 'Yes', 'Market Square', 4.4, 'Yes', 'No', 'No', 'Yes', 'Yes', 'No', 'Yes'),
('Sushi Express', 'Modern', 'Japanese Cuisine', '$$', 'Yes', 'City Center', 4.5, 'Yes', 'Yes', 'No', 'No', 'Yes', 'No', 'No'),
('Pizza Hub', 'Casual', 'Italian Cuisine', '$$', 'Yes', 'Suburbs', 4.2, 'Yes', 'No', 'Yes', 'No', 'Yes', 'No', 'Yes'),
('Fine Dine', 'Elegant', 'International Cuisine', '$$$$', 'No', 'Luxury District', 4.9, 'Yes', 'Yes', 'Yes', 'No', 'No', 'No', 'No'),
('Ramen House', 'Cozy', 'Japanese Cuisine', '$$', 'Yes', 'Market District', 4.4, 'Yes', 'No', 'Yes', 'No', 'Yes', 'No', 'Yes'),
('Thai Spice', 'Modern', 'Thai Cuisine', '$$', 'Yes', 'Asian District', 4.6, 'Yes', 'Yes', 'Yes', 'No', 'Yes', 'No', 'Yes'),
('El Rastro', 'Elegant', 'Spanish Cuisine', '$', 'Yes', 'Madrid Street 1', 4.6, 'Yes', 'Yes', 'Yes', 'Yes', 'No', 'Yes', 'No'),
('La Casa del Tapas', 'Romantic', 'Spanish Cuisine', '$$', 'Yes', 'Barcelona Road 2', 4.4, 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes'),
('Bodega de Espana', 'Cozy', 'Spanish Cuisine', '$$$', 'No', 'Seville Avenue 3', 4.5, 'Yes', 'Yes', 'Yes', 'Yes', 'No', 'Yes', 'No'),
('Taberna del Sol', 'Modern', 'Spanish Cuisine', '$$$$', 'Yes', 'Granada Lane 4', 4.7, 'Yes', 'Yes', 'Yes', 'No', 'Yes', 'Yes', 'Yes'),
('Osteria Roma', 'Family-friendly', 'Italian Cuisine', '$', 'Yes', 'Rome Street 5', 4.3, 'No', 'Yes', 'No', 'No', 'Yes', 'No', 'Yes'),
('Bella Italia', 'Traditional', 'Italian Cuisine', '$$', 'Yes', 'Florence Road 6', 4.2, 'Yes', 'No', 'Yes', 'No', 'Yes', 'No', 'Yes'),
('Trattoria Toscana', 'Elegant', 'Italian Cuisine', '$$$', 'No', 'Venice Avenue 7', 4.4, 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes'),
('La Dolce Vita', 'Modern', 'Italian Cuisine', '$$$$', 'Yes', 'Milan Lane 8', 4.6, 'Yes', 'Yes', 'Yes', 'Yes', 'No', 'Yes', 'Yes'),
('Sushi Zen', 'Casual', 'Japanese Cuisine', '$', 'Yes', 'Tokyo Street 9', 4.9, 'Yes', 'Yes', 'Yes', 'Yes', 'No', 'Yes', 'Yes'),
('Nihon Delight', 'Modern', 'Japanese Cuisine', '$$', 'No', 'Kyoto Road 10', 4.8, 'Yes', 'No', 'No', 'Yes', 'Yes', 'Yes', 'Yes'),
('Sakura Garden', 'Elegant', 'Japanese Cuisine', '$$$', 'Yes', 'Osaka Avenue 11', 4.7, 'Yes', 'No', 'No', 'Yes', 'Yes', 'Yes', 'No'),
('Zen Palace', 'Romantic', 'Japanese Cuisine', '$$$$', 'Yes', 'Hiroshima Lane 12', 4.8, 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'No'),
('Burger Haven', 'Casual', 'American Cuisine', '$', 'Yes', 'New York Street 13', 3.8, 'Yes', 'Yes', 'No', 'Yes', 'Yes', 'Yes', 'Yes'),
('Grill Master', 'Cozy', 'American Cuisine', '$$', 'Yes', 'Chicago Road 14', 3.9, 'Yes', 'No', 'Yes', 'Yes', 'Yes', 'No', 'Yes'),
('The Rib Shack', 'Family-friendly', 'American Cuisine', '$$$', 'Yes', 'Los Angeles Avenue 15', 4, 'No', 'No', 'Yes', 'No', 'No', 'Yes', 'Yes'),
('Steakhouse Prime', 'Elegant', 'American Cuisine', '$$$$', 'No', 'Houston Lane 16', 4.2, 'Yes', 'Yes', 'Yes', 'Yes', 'No', 'No', 'Yes'),
('Curry Palace', 'Family-friendly', 'Indian Cuisine', '$', 'Yes', 'Delhi Street 17', 4.1, 'Yes', 'Yes', 'No', 'No', 'Yes', 'Yes', 'Yes'),
('Spice Junction', 'Traditional', 'Indian Cuisine', '$$', 'Yes', 'Mumbai Road 18', 4.3, 'Yes', 'No', 'Yes', 'No', 'Yes', 'Yes', 'Yes'),
('Tandoori Nights', 'Elegant', 'Indian Cuisine', '$$$', 'No', 'Kolkata Avenue 19', 4.5, 'Yes', 'No', 'No', 'No', 'Yes', 'Yes', 'No'),
('Masala Bistro', 'Modern', 'Indian Cuisine', '$$$$', 'Yes', 'Bangalore Lane 20', 4.4, 'No', 'Yes', 'Yes', 'Yes', 'No', 'No', 'Yes'),
('Green Eats', 'Eco-friendly', 'Vegan Cuisine', '$', 'No', 'Portland Street 21', 4.2, 'Yes', 'Yes', 'Yes', 'No', 'Yes', 'Yes', 'Yes'),
('Vegan Delight', 'Family-friendly', 'Vegan Cuisine', '$$', 'Yes', 'Seattle Road 22', 4.3, 'No', 'Yes', 'Yes', 'No', 'Yes', 'Yes', 'Yes'),
('Pure Vegan', 'Cozy', 'Vegan Cuisine', '$$$', 'No', 'San Francisco Avenue 23', 4.4, 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes'),
('The Green Table', 'Modern', 'Vegan Cuisine', '$$$$', 'Yes', 'Los Angeles Lane 24', 4.5, 'Yes', 'Yes', 'No', 'No', 'Yes', 'Yes', 'Yes'),
('Taco Fiesta', 'Traditional', 'Mexican Cuisine', '$', 'Yes', 'Mexico City Street 25', 4, 'Yes', 'Yes', 'No', 'Yes', 'Yes', 'No', 'No'),
('El Camino', 'Family-friendly', 'Mexican Cuisine', '$$', 'Yes', 'Cancun Road 26', 4.1, 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'No', 'Yes'),
('La Cantina', 'Cozy', 'Mexican Cuisine', '$$$', 'No', 'Guadalajara Avenue 27', 4.2, 'No', 'Yes', 'Yes', 'Yes', 'No', 'Yes', 'Yes'),
('Burrito Bonanza', 'Modern', 'Mexican Cuisine', '$$$$', 'Yes', 'Tijuana Lane 28', 4.3, 'Yes', 'Yes', 'Yes', 'Yes', 'No', 'Yes', 'No'),
('Panda Palace', 'Elegant', 'Chinese Cuisine', '$', 'Yes', 'Beijing Street 29', 4.5, 'Yes', 'Yes', 'No', 'No', 'No', 'No', 'No'),
('Dynasty Diner', 'Modern', 'Chinese Cuisine', '$$', 'Yes', 'Shanghai Road 30', 4.4, 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'No'),
('Great Wall', 'Casual', 'Chinese Cuisine', '$$$', 'No', 'Hong Kong Avenue 31', 4.6, 'Yes', 'No', 'Yes', 'Yes', 'No', 'No', 'Yes'),
('Mandarin Delight', 'Romantic', 'Chinese Cuisine', '$$$$', 'Yes', 'Taipei Lane 32', 4.7, 'Yes', 'Yes', 'Yes', 'No', 'Yes', 'Yes', 'No'),
('Chez Pierre', 'Romantic', 'French Cuisine', '$', 'No', 'Paris Street 33', 4.7, 'Yes', 'Yes', 'Yes', 'No', 'Yes', 'No', 'Yes'),
('Le Bistro', 'Elegant', 'French Cuisine', '$$', 'No', 'Lyon Road 34', 4.6, 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'No', 'Yes'),
('La Belle Epoque', 'Modern', 'French Cuisine', '$$$', 'Yes', 'Nice Avenue 35', 4.8, 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'No', 'Yes'),
('Gourmet Paris', 'Traditional', 'French Cuisine', '$$$$', 'Yes', 'Marseille Lane 36', 4.9, 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'No'),
('Ocean Grill', 'Vibrant', 'Seafood', '$', 'Yes', 'Sydney Street 37', 4.8, 'Yes', 'Yes', 'No', 'No', 'Yes', 'Yes', 'Yes'),
('Seafood Bistro', 'Elegant', 'Seafood', '$$', 'Yes', 'Auckland Road 38', 4.7, 'No', 'No', 'No', 'Yes', 'Yes', 'No', 'Yes'),
('Nautical Delights', 'Modern', 'Seafood', '$$$', 'Yes', 'Wellington Avenue 39', 4.6, 'Yes', 'No', 'Yes', 'Yes', 'No', 'Yes', 'Yes'),
('The Crab Shack', 'Casual', 'Seafood', '$$$$', 'Yes', 'Dunedin Lane 40', 4.5, 'No', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes'),
('Tandoori Palace', 'Family-friendly', 'Indian Cuisine', '$', 'Yes', 'Mumbai Street 1', 4.2, 'No', 'Yes', 'Yes', 'Yes', 'Yes', 'No', 'No'),
('Curry House', 'Cozy', 'Indian Cuisine', '$$', 'Yes', 'Delhi Road 2', 4.3, 'Yes', 'Yes', 'Yes', 'Yes', 'No', 'Yes', 'Yes'),
('Spice Bistro', 'Elegant', 'Indian Cuisine', '$$$', 'No', 'Bangalore Avenue 3', 4.5, 'No', 'Yes', 'Yes', 'Yes', 'Yes', 'No', 'No'),
('Masala Kitchen', 'Modern', 'Indian Cuisine', '$$$$', 'Yes', 'Chennai Lane 4', 4.6, 'Yes', 'No', 'Yes', 'Yes', 'Yes', 'Yes', 'No'),
('Dragon Wok', 'Casual', 'Chinese Cuisine', '$', 'Yes', 'Shanghai Street 5', 4.1, 'No', 'No', 'No', 'Yes', 'Yes', 'Yes', 'No'),
('Panda Garden', 'Family-friendly', 'Chinese Cuisine', '$$', 'Yes', 'Beijing Road 6', 4.2, 'No', 'Yes', 'Yes', 'Yes', 'No', 'No', 'No'),
('Mandarin Delight', 'Elegant', 'Chinese Cuisine', '$$$', 'No', 'Hong Kong Avenue 7', 4.4, 'No', 'No', 'Yes', 'No', 'Yes', 'No', 'No'),
('Great Wall', 'Modern', 'Chinese Cuisine', '$$$$', 'Yes', 'Taipei Lane 8', 4.5, 'No', 'No', 'Yes', 'No', 'Yes', 'No', 'No'),
('La Dolce Vita', 'Cozy', 'Italian Cuisine', '$$$', 'No', 'Venice Avenue 27', 4.7, 'Yes', 'No', 'Yes', 'Yes', 'No', 'Yes', 'Yes'),
('Trattoria Bella', 'Modern', 'Italian Cuisine', '$$$$', 'Yes', 'Milan Lane 28', 4.8, 'Yes', 'Yes', 'No', 'No', 'Yes', 'Yes', 'Yes'),
('The Great Wall', 'Modern', 'Chinese Cuisine', '$$$$', 'Yes', 'Guangzhou Lane 8', 4.6, 'No', 'Yes', 'No', 'Yes', 'No', 'Yes', 'No'),
('Mediterranean Grill', 'Elegant', 'Arabic Cuisine', '$', 'Yes', 'Dubai Street 9', 4.3, 'Yes', 'Yes', 'Yes', 'No', 'Yes', 'Yes', 'Yes'),
('Aladdins Kitchen', 'Romantic', 'Arabic Cuisine', '$$', 'Yes', 'Cairo Road 10', 4.4, 'Yes', 'Yes', 'Yes', 'No', 'Yes', 'No', 'Yes'),
('Oasis Restaurant', 'Cozy', 'Arabic Cuisine', '$$$', 'No', 'Riyadh Avenue 11', 4.5, 'No', 'No', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes'),
('Arabian Nights', 'Modern', 'Arabic Cuisine', '$$$$', 'Yes', 'Doha Lane 12', 4.6, 'Yes', 'No', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes'),
('Quick Bites', 'Casual', 'Fastfood', '$', 'Yes', 'New York Street 13', 3.8, 'Yes', 'Yes', 'Yes', 'No', 'No', 'No', 'Yes'),
('Fast Feast', 'Family-friendly', 'Fastfood', '$$', 'Yes', 'Chicago Road 14', 3.9, 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes'),
('Burger King', 'Modern', 'Fastfood', '$$$', 'Yes', 'Los Angeles Avenue 15', 4.0, 'Yes', 'Yes', 'Yes', 'Yes', 'No', 'No', 'Yes'),
('Fries and Shakes', 'Cozy', 'Fastfood', '$$$$', 'No', 'Houston Lane 16', 4.1, 'Yes', 'Yes', 'Yes', 'Yes', 'No', 'No', 'Yes'),
('Sakura Sushi', 'Elegant', 'Japanese Cuisine', '$', 'Yes', 'Tokyo Street 17', 4.7, 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'No', 'Yes'),
('Nihon Ramen', 'Modern', 'Japanese Cuisine', '$$', 'No', 'Kyoto Road 18', 4.6, 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes'),
('Zen Sushi', 'Casual', 'Japanese Cuisine', '$$$', 'Yes', 'Osaka Avenue 19', 4.8, 'Yes', 'No', 'No', 'Yes', 'Yes', 'Yes', 'No'),
('Samurai Grill', 'Romantic', 'Japanese Cuisine', '$$$$', 'Yes', 'Hiroshima Lane 20', 4.9, 'Yes', 'Yes', 'Yes', 'No', 'Yes', 'No', 'Yes'),
('Thai Paradise', 'Family-friendly', 'Thai Cuisine', '$', 'Yes', 'Bangkok Street 21', 4.0, 'No', 'Yes', 'No', 'No', 'Yes', 'No', 'Yes'),
('Spicy Thai', 'Casual', 'Thai Cuisine', '$$', 'Yes', 'Chiang Mai Road 22', 4.1, 'No', 'Yes', 'No', 'No', 'Yes', 'Yes', 'Yes'),
('Thai Fusion', 'Elegant', 'Thai Cuisine', '$$$', 'No', 'Phuket Avenue 23', 4.3, 'Yes', 'No', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes'),
('The Thai Table', 'Modern', 'Thai Cuisine', '$$$$', 'Yes', 'Hua Hin Lane 24', 4.4, 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes'),
('Roma Ristorante', 'Elegant', 'Italian Cuisine', '$', 'Yes', 'Rome Street 25', 4.5, 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'No'),
('Pasta House', 'Family-friendly', 'Italian Cuisine', '$$', 'Yes', 'Florence Road 26', 4.6, 'Yes', 'Yes', 'No', 'No', 'Yes', 'Yes', 'Yes');
COMMIT;
